# Generated by Django 4.2.25 on 2026-06-30 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('family_role', models.CharField(choices=[('爸爸', '爸爸'), ('妈妈', '妈妈'), ('孩子', '孩子'), ('长辈', '长辈')], max_length=20, verbose_name='家庭身份')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='菜品名称')),
                ('category', models.CharField(choices=[('素菜', '素菜'), ('荤菜', '荤菜'), ('汤品', '汤品'), ('凉菜', '凉菜'), ('小吃', '小吃')], max_length=20, verbose_name='分类')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='菜品图片存储路径')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='口味、制作步骤描述')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
                'db_table': 'dish',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='饮品名称')),
                ('spec', models.CharField(blank=True, max_length=30, null=True, verbose_name='规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='单品售价')),
                ('is_lactose', models.BooleanField(default=False, verbose_name='是否含乳糖')),
            ],
            options={
                'verbose_name': '饮品',
                'verbose_name_plural': '饮品',
                'db_table': 'drink',
            },
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='水果名称')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片路径')),
                ('store_tip', models.TextField(blank=True, null=True, verbose_name='储存建议')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='基础参考单价')),
                ('is_allergy', models.BooleanField(default=False, verbose_name='是否易过敏')),
            ],
            options={
                'verbose_name': '水果',
                'verbose_name_plural': '水果',
                'db_table': 'fruit',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=50, verbose_name='所属地区')),
                ('market_name', models.CharField(max_length=50, verbose_name='菜市场名称')),
                ('address', models.TextField(blank=True, null=True, verbose_name='详细地址')),
            ],
            options={
                'verbose_name': '菜市场',
                'verbose_name_plural': '菜市场',
                'db_table': 'market',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='食材名称')),
                ('type', models.CharField(choices=[('蔬菜', '蔬菜'), ('肉类', '肉类'), ('水果', '水果'), ('干货', '干货')], max_length=20, verbose_name='分类')),
                ('season', models.CharField(choices=[('春', '春'), ('夏', '夏'), ('秋', '秋'), ('冬', '冬'), ('全年', '全年')], max_length=20, verbose_name='季节')),
            ],
            options={
                'verbose_name': '食材',
                'verbose_name_plural': '食材',
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='下单日期')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='采购总花费')),
                ('purchase_text', models.TextField(verbose_name='完整采购清单文本')),
                ('is_finish', models.BooleanField(default=False, verbose_name='是否已采购')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '点餐订单',
                'verbose_name_plural': '点餐订单',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='UserTaboo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taboo_name', models.CharField(max_length=50, verbose_name='忌口食材名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户忌口',
                'verbose_name_plural': '用户忌口',
                'db_table': 'user_taboo',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_num', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='剩余库存数量')),
                ('tip', models.CharField(blank=True, max_length=100, null=True, verbose_name='过期备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='库存更新时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='对应食材')),
            ],
            options={
                'verbose_name': '家庭库存',
                'verbose_name_plural': '家庭库存',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_type', models.CharField(choices=[('dish', '菜品'), ('fruit', '水果'), ('drink', '饮品')], max_length=10, verbose_name='商品类型')),
                ('goods_id', models.IntegerField(verbose_name='对应商品id')),
                ('buy_num', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='购买份数')),
                ('eat_time', models.CharField(choices=[('早餐', '早餐'), ('午餐', '午餐'), ('晚餐', '晚餐'), ('加餐', '加餐')], max_length=10, verbose_name='用餐时段')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='当日零售单价')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='价格更新日期')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.market', verbose_name='所属菜市场')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='对应食材')),
            ],
            options={
                'verbose_name': '食材市场价',
                'verbose_name_plural': '食材市场价',
                'db_table': 'market_price',
            },
        ),
        migrations.CreateModel(
            name='DishMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('need_num', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='菜品所需食材数量')),
                ('unit', models.CharField(choices=[('斤', '斤'), ('个', '个'), ('颗', '颗'), ('盒', '盒'), ('把', '把')], max_length=10, verbose_name='单位')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dish', verbose_name='对应菜品')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='对应食材')),
            ],
            options={
                'verbose_name': '菜品食材',
                'verbose_name_plural': '菜品食材',
                'db_table': 'dish_material',
            },
        ),
        migrations.CreateModel(
            name='UserCollect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_type', models.CharField(choices=[('dish', '菜品'), ('fruit', '水果'), ('drink', '饮品')], max_length=10, verbose_name='商品类型')),
                ('goods_id', models.IntegerField(verbose_name='对应商品id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'db_table': 'user_collect',
                'unique_together': {('user', 'goods_type', 'goods_id')},
            },
        ),
    ]
