# Generated by Django 4.2.25 on 2026-06-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='基础参考单价'),
        ),
    ]
