# Generated by Django 4.2.25 on 2026-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dish_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='base_price',
        ),
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='参考单价(元/斤)'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(default='斤', max_length=20, verbose_name='单位'),
        ),
    ]
